name: todos_repository

version: 1.0.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.4
  rxdart: ^0.24.1
  hive: ^1.4.4
  meta: ^1.2.2
  uuid: ^2.2.2
  path_provider: ^1.6.14
  hive_flutter: ^0.3.1

dev_dependencies:
  hive_generator: ^0.7.1
  bloc_test: ^7.0.0
  mockito: ^4.1.1
  build_runner: ^1.10.2

